# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'doc/**'
    - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'doc/**'
    - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_RESULTS_PATH: ${{ github.workspace }}/artifacts/test-results/test-results.trx

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=$TEST_RESULTS_PATH"

    - uses: dorny/test-reporter@v1
      if: success() || failure()  
      with:
        name: .NET Test Results
        path: $TEST_RESULTS_PATH
        reporter: dotnet-trx
